import process from "node:process";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { defineConfig } from "vitest/config";

// The GitHub Pages base path is injected by the `pages.yml` workflow via
// VITE_BASE so the same bundle works at `/`, `/checklist/`, or any subpath.
const base = process.env.VITE_BASE ?? "/";

export default defineConfig({
  base,
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: "autoUpdate",
      // Static assets copied verbatim from `public/` that the service
      // worker should also precache so the install / favicon / iOS
      // home-screen icon resolve offline. The `icons` array below is
      // precached automatically via the workbox glob; these are the
      // extras that aren't manifest icons.
      includeAssets: [
        "favicon.svg",
        "favicon.ico",
        "apple-touch-icon-180x180.png",
      ],
      manifest: {
        id: base,
        scope: base,
        start_url: base,
        name: "checklist",
        short_name: "checklist",
        description:
          "A local-first PWA checklist app with template and sharing support.",
        theme_color: "#1f2933",
        background_color: "#1f2933",
        display: "standalone",
        orientation: "any",
        lang: "en",
        categories: ["productivity", "utilities"],
        // Generated by `make icons` from `public/favicon.svg`; see
        // `pwa-assets.config.ts`. Keep this list in sync with the PNGs
        // committed under `public/`.
        icons: [
          { src: "pwa-64x64.png", sizes: "64x64", type: "image/png" },
          { src: "pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "pwa-512x512.png", sizes: "512x512", type: "image/png" },
          {
            src: "maskable-icon-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      workbox: {
        // Precache the app shell: JS, CSS, fonts, icons, and the HTML
        // entry. Source maps stay on the network — they don't need to
        // be available offline.
        globPatterns: ["**/*.{js,css,html,svg,png,ico,webp,woff2}"],
        // Source maps stay on the network. The non-default webfont
        // families (Inter / Source Serif 4 / OpenDyslexic) load on demand
        // when the user picks them in Appearance (see `src/theme/fonts.ts`)
        // and HTTP-cache afterwards, so keep them out of the precache —
        // only JetBrains Mono (the default face) ships in the app shell.
        globIgnores: [
          "**/*.map",
          "**/inter-*.woff2",
          "**/source-serif-4-*.woff2",
          "**/opendyslexic-*.woff2",
        ],
        cleanupOutdatedCaches: true,
        // App shell is precached; cloud-storage hosts use networkFirst.
        runtimeCaching: [
          {
            urlPattern: ({ url }) =>
              url.hostname === "www.googleapis.com" ||
              url.hostname === "api.dropboxapi.com" ||
              url.hostname === "content.dropboxapi.com",
            handler: "NetworkFirst",
            options: { cacheName: "cloud-storage" },
          },
        ],
      },
    }),
  ],
  test: {
    // Domain/storage/share tests run in node. UI tests opt into jsdom with a
    // `// @vitest-environment jsdom` docblock at the top of the file.
    environment: "node",
    globals: true,
    include: ["tests/**/*.test.{ts,tsx}"],
  },
});
