import { readFileSync } from "node:fs";
import process from "node:process";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { defineConfig, type Plugin } from "vitest/config";

// The GitHub Pages base path is injected by the `pages.yml` workflow via
// VITE_BASE so the same bundle works at `/`, `/checklist/`, or any subpath.
const base = process.env.VITE_BASE ?? "/";

const pkg = JSON.parse(
  readFileSync(new URL("./package.json", import.meta.url), "utf8"),
) as { version: string };

// Short build identifier rendered next to the "checklist" header and
// surfaced in the update prompt so you can tell at a glance which build
// is running. Shape: `<pkg.version>[.<run>][-<slot>][+<commit>]`:
//
//   - `<run>`    — the `GITHUB_RUN_NUMBER` GitHub Actions populates
//                  automatically (omitted for local builds).
//   - `<slot>`   — `pre` for the `/preview/` slot, `br` for `/branch/`,
//                  omitted for the production `/` slot.
//   - `<commit>` — the short `GITHUB_SHA` as semver build metadata after
//                  the `+` (omitted for local builds).
//
// e.g. `0.1.0` for a local build, `0.1.0.42-pre+a1b2c3d` for a CI
// preview build. Mirrors budget's BUILD_LABEL, extended with the commit
// hash.
const GITHUB_RUN_NUMBER = process.env.GITHUB_RUN_NUMBER;
const COMMIT_HASH = (process.env.GITHUB_SHA ?? "").slice(0, 7);
const BUILD_SLOT =
  base === "/preview/" ? "pre" : base === "/branch/" ? "br" : "";
const BUILD_LABEL =
  pkg.version +
  (GITHUB_RUN_NUMBER ? `.${GITHUB_RUN_NUMBER}` : "") +
  (BUILD_SLOT ? `-${BUILD_SLOT}` : "") +
  (COMMIT_HASH ? `+${COMMIT_HASH}` : "");

// Emit a tiny `version.json` carrying this build's BUILD_LABEL into the
// slot root (`/version.json`, `/preview/version.json`, …). The running
// page knows only its OWN BUILD_LABEL, so the update prompt can't name
// the *incoming* build from anything in the loaded bundle. It fetches
// this file (cache-bypassed) when the workbox `waiting` event fires to
// learn the version it's about to upgrade to. Deliberately kept out of
// precache (`json` isn't in `workbox.globPatterns`) so the active SW
// lets the fetch reach the network and return the freshly-deployed file.
function emitVersionJson(): Plugin {
  return {
    name: "emit-version-json",
    apply: "build",
    generateBundle() {
      this.emitFile({
        type: "asset",
        fileName: "version.json",
        source: `${JSON.stringify({ version: BUILD_LABEL })}\n`,
      });
    },
  };
}

// Mirror the built `index.html` to `privacy/index.html` so GitHub Pages
// serves the SPA from the clean URL `/privacy/` (and `/preview/privacy/`,
// …). The app's `main.tsx` reads `location.pathname` and mounts the
// privacy page there; the copied HTML loads the same hashed asset URLs
// (they are origin-absolute), so no rewrite is needed. Runs late so the
// PWA plugin's manifest-link injection is already baked into the source.
function emitPrivacyAlias(): Plugin {
  return {
    name: "emit-privacy-alias",
    apply: "build",
    enforce: "post",
    generateBundle(_options, bundle) {
      const index = bundle["index.html"];
      if (index && index.type === "asset") {
        this.emitFile({
          type: "asset",
          fileName: "privacy/index.html",
          source: index.source,
        });
      }
    },
  };
}

export default defineConfig({
  base,
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      // `UpdateToast` registers the SW itself via `workbox-window` (so it
      // can pass `updateViaCache: "none"`) and the new build parks in the
      // `waiting` state until the user clicks Reload — no silent swap, no
      // auto-injected `<script>`.
      registerType: "prompt",
      injectRegister: null,
      // Static assets copied verbatim from `public/` that the service
      // worker should also precache so the install / favicon / iOS
      // home-screen icon resolve offline. The `icons` array below is
      // precached automatically via the workbox glob; these are the
      // extras that aren't manifest icons.
      includeAssets: [
        "favicon.svg",
        "favicon.ico",
        "apple-touch-icon-180x180.png",
      ],
      manifest: {
        id: base,
        scope: base,
        start_url: base,
        name: "checklist",
        short_name: "checklist",
        description:
          "A local-first PWA checklist app with template and sharing support.",
        theme_color: "#1f2933",
        background_color: "#1f2933",
        display: "standalone",
        orientation: "any",
        lang: "en",
        categories: ["productivity", "utilities"],
        // Generated by `make icons` from `public/favicon.svg`; see
        // `pwa-assets.config.ts`. Keep this list in sync with the PNGs
        // committed under `public/`.
        icons: [
          { src: "pwa-64x64.png", sizes: "64x64", type: "image/png" },
          { src: "pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "pwa-512x512.png", sizes: "512x512", type: "image/png" },
          {
            src: "maskable-icon-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      workbox: {
        // Precache the app shell: JS, CSS, fonts, icons, and the HTML
        // entry. Source maps stay on the network — they don't need to
        // be available offline.
        globPatterns: ["**/*.{js,css,html,svg,png,ico,webp,woff2}"],
        // Source maps stay on the network. The non-default webfont
        // families (Inter / Source Serif 4 / OpenDyslexic) load on demand
        // when the user picks them in Appearance (see `src/theme/fonts.ts`)
        // and HTTP-cache afterwards, so keep them out of the precache —
        // only JetBrains Mono (the default face) ships in the app shell.
        globIgnores: [
          "**/*.map",
          "**/inter-*.woff2",
          "**/source-serif-4-*.woff2",
          "**/opendyslexic-*.woff2",
        ],
        cleanupOutdatedCaches: true,
        // App shell is precached; cloud-storage hosts use networkFirst.
        runtimeCaching: [
          {
            urlPattern: ({ url }) =>
              url.hostname === "www.googleapis.com" ||
              url.hostname === "api.dropboxapi.com" ||
              url.hostname === "content.dropboxapi.com",
            handler: "NetworkFirst",
            options: { cacheName: "cloud-storage" },
          },
        ],
      },
    }),
    emitVersionJson(),
    emitPrivacyAlias(),
  ],
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
    __BUILD_LABEL__: JSON.stringify(BUILD_LABEL),
  },
  test: {
    // Domain/storage/share tests run in node. UI tests opt into jsdom with a
    // `// @vitest-environment jsdom` docblock at the top of the file.
    environment: "node",
    globals: true,
    include: ["tests/**/*.test.{ts,tsx}"],
  },
});
