// Register the service worker generated by vite-plugin-pwa. Registration only
// happens in production builds; in dev the virtual module is a no-op.

import { registerSW } from "virtual:pwa-register";

export function registerServiceWorker(): void {
  if (import.meta.env.PROD) {
    registerSW({ immediate: true });
  }
}
