// Wires the Home Screen widgets into both native projects during
// `expo prebuild`.
//
// iOS: the WidgetKit extension *target* is generated by `@bacons/apple-targets`
// (see `../targets/widget`), so this plugin only adds the App Group entitlement
// to the **main app** so it can share a container with that extension. The
// widget's own App Group is declared in its `expo-target.config.js`.
//
// Android: Glance widgets are plain app-widget providers, so this plugin copies
// the Kotlin sources and the provider XML into the app module and registers the
// `<receiver>` in the manifest. Anything under `src/main` is packed into the
// APK automatically, so no Gradle change is needed. The `checklist://` deep
// link the widgets open is already registered from `app.json`'s `scheme`.

const fs = require("node:fs");
const path = require("node:path");
const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
  withEntitlementsPlist,
  withStringsXml,
} = require("expo/config-plugins");

const APP_GROUP = "group.se.niclaslindstedt.checklist";
const ANDROID_PKG = "se.niclaslindstedt.checklist.widget";
const RECEIVER = `${ANDROID_PKG}.ChecklistGlanceWidgetReceiver`;

function copyFile(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}

module.exports = function withWidgets(config) {
  // iOS: the main app joins the App Group so it can write the container the
  // widget extension reads. (The extension declares the same group itself.)
  config = withEntitlementsPlist(config, (c) => {
    const key = "com.apple.security.application-groups";
    const groups = new Set(c.modResults[key] ?? []);
    groups.add(APP_GROUP);
    c.modResults[key] = [...groups];
    return c;
  });

  // Android: copy the Glance widget sources + provider XML into the app module.
  config = withDangerousMod(config, [
    "android",
    (c) => {
      const src = path.join(c.modRequest.projectRoot, "widgets", "android");
      const appRoot = path.join(
        c.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
      );
      const javaDir = path.join(appRoot, "java", ...ANDROID_PKG.split("."));
      for (const file of fs.readdirSync(src)) {
        if (file.endsWith(".kt")) {
          copyFile(path.join(src, file), path.join(javaDir, file));
        }
      }
      copyFile(
        path.join(src, "checklist_widget_info.xml"),
        path.join(appRoot, "res", "xml", "checklist_widget_info.xml"),
      );
      return c;
    },
  ]);

  // Android: the widget's description string the provider XML references.
  config = withStringsXml(config, (c) => {
    c.modResults = AndroidConfig.Strings.setStringItem(
      [
        {
          $: { name: "checklist_widget_description", translatable: "false" },
          _: "Your active checklist at a glance",
        },
      ],
      c.modResults,
    );
    return c;
  });

  // Android: register the Glance receiver as an app-widget provider.
  config = withAndroidManifest(config, (c) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(c.modResults);
    app.receiver = app.receiver ?? [];
    const exists = app.receiver.some((r) => r.$?.["android:name"] === RECEIVER);
    if (!exists) {
      app.receiver.push({
        $: {
          "android:name": RECEIVER,
          "android:exported": "true",
          "android:label": "@string/checklist_widget_description",
        },
        "intent-filter": [
          {
            action: [
              {
                $: {
                  "android:name": "android.appwidget.action.APPWIDGET_UPDATE",
                },
              },
            ],
          },
        ],
        "meta-data": [
          {
            $: {
              "android:name": "android.appwidget.provider",
              "android:resource": "@xml/checklist_widget_info",
            },
          },
        ],
      });
    }
    return c;
  });

  return config;
};
